scalacOptions ++= Seq("-deprecation", "-feature")

addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "0.2.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "0.7.1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.2.5")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"    % "0.3.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"       % "0.8.4")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"   % "0.5.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"      % "0.8.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.2.0")
