scalacOptions ++= Seq("-deprecation", "-feature")

addSbtPlugin("com.github.gseitz" % "sbt-release"           % "1.0.8")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"          % "2.3")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"               % "1.1.0")
// addSbtPlugin("com.eed3si9n"      % "sbt-export-repo"       % "0.1.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"         % "0.7.0")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"            % "0.4.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"               % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"           % "0.6.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"              % "1.3.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"         % "1.5.1")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
