scalacOptions ++= Seq("-deprecation", "-feature")

addSbtPlugin("com.github.gseitz" % "sbt-release"           % "1.0.13")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"          % "3.9.4")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"               % "2.0.1")
// addSbtPlugin("com.eed3si9n"      % "sbt-export-repo"       % "0.1.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"         % "0.10.0")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"            % "0.4.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"               % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"           % "0.6.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"              % "1.4.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"         % "1.6.1")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"       % "2.4.10")
addSbtPlugin("de.heikoseeberger" % "sbt-header"            % "5.6.0")
